### ISSUE TITLE
Toggle Memer does not work

### ISSUE THREAD

**Issue by CheAle14** [CheAle14/bot-source-code#32]
```
07:31:53.096   [Error] CmdHandle: System.NullReferenceException: Object reference not set to an instance of an object.
    ...                        at Casino.FourAcesCasino.<>c__DisplayClass37_0.<GetTGCUser>b__0(TGCUser x) in D:\_GitHub\bot-source-code\src\Casino\FourAcesCasino.cs:line 127
    ...                        at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
    ...                        at Casino.FourAcesCasino.GetTGCUser(SocketGuildUser user) in D:\_GitHub\bot-source-code\src\Casino\FourAcesCasino.cs:line 127
    ...                        at DiscordBot.Attributes.RequireAllowedToggleRole.CheckPermissionsAsync(ICommandContext context, CommandInfo command, IServiceProvider services) in D:\_GitHub\bot-source-code\src\Attributes\RequireAllowedToggleRole.cs:line 20
    ...                        at Discord.Commands.CommandInfo.<>c__DisplayClass41_0.<<CheckPreconditionsAsync>g__CheckGroups|0>d.MoveNext()
    ...                     --- End of stack trace from previous location where exception was thrown ---
    ...                        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...                        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    ...                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    ...                        at Discord.Commands.CommandInfo.<CheckPreconditionsAsync>d__41.MoveNext()
    ...                     --- End of stack trace from previous location where exception was thrown ---
    ...                        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...                        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    ...                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    ...                        at Discord.Commands.CommandService.<ExecuteAsync>d__53.MoveNext()
    ...                     --- End of stack trace from previous location where exception was thrown ---
    ...                        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...                        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    ...                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    ...                        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
    ...                        at DiscordBot.CommandHandler.<OnMessageReceivedAsync>d__8.MoveNext() in D:\_GitHub\bot-source-code\src\Services\CommandHandler.cs:line 146
```

**Comment by CheAle14** [comment]
Fixed.
